class GuildAuditJob < ApplicationJob
  queue_as :default

  def perform(response_url)
    verified_ids = Rails.cache.read("guild_audit_verified_ids") || Set.new
    signups = GuildSignup.where.not(id: verified_ids.to_a).includes(:user, :guild).to_a
    blocked_domains = GuildSignupProtection.blocked_domains

    definitely_suspicious = []
    possibly_suspicious = []


    signups.each do |signup|
      domain = signup.email.to_s.split("@").last&.downcase
      flags = []

      if domain.present? && blocked_domains.include?(domain)
        flags << "disposable email domain (`#{domain}`)"
      end

      if flags.any?
        definitely_suspicious << { signup: signup, flags: flags }
      end
    end

    suspicious_domain_groups = signups
      .select { |s| blocked_domains.include?(s.email.to_s.split("@").last&.downcase) }
      .group_by { |s| s.email.to_s.split("@").last&.downcase }

    suspicious_domain_groups.each do |domain, group|
      names = group.map { |s| s.name.to_s.strip.downcase }.uniq
      if names.size > 1
        existing_ids = definitely_suspicious.map { |d| d[:signup].id }
        group.each do |signup|
          next if existing_ids.include?(signup.id)
          definitely_suspicious << { signup: signup, flags: [ "multiple names on suspicious domain `#{domain}` (#{names.size} unique names)" ] }
        end
      end
    end


    signups.each do |signup|
      next if definitely_suspicious.any? { |d| d[:signup].id == signup.id }

      flags = []
      name = signup.name.to_s.strip
      email_local = signup.email.to_s.split("@").first

      if random_name?(name)
        flags << "random-looking name"
      end

      if autogenerated_email?(email_local)
        flags << "auto-generated email pattern"
      end

      if flags.any?
        possibly_suspicious << { signup: signup, flags: flags }
      end
    end

    bulk_groups = signups.group_by { |s| [ s.guild_id, s.country.to_s.downcase ] }
    bulk_flags = {}

    bulk_groups.each do |(guild_id, country), group|
      next if group.size < 5

      sorted = group.sort_by(&:created_at)
      sorted.each_with_index do |signup, i|
        window = sorted[i, 5]
        break if window.size < 5
        if (window.last.created_at - window.first.created_at) <= 1.hour
          window.each do |s|
            count = window.size
            bulk_flags[s.id] = [ count, bulk_flags[s.id]&.first || 0 ].max
          end
        end
      end
    end

    bulk_flags.each do |id, (count, _)|
      signup = signups.find { |s| s.id == id }
      next unless signup
      next if definitely_suspicious.any? { |d| d[:signup].id == id }

      existing = possibly_suspicious.find { |p| p[:signup].id == id }
      flag = "part of #{count} signups to #{signup.guild&.city || 'unknown'} within 1 hour"
      if existing
        existing[:flags] << flag
      else
        possibly_suspicious << { signup: signup, flags: [ flag ] }
      end
    end

    report = build_report(definitely_suspicious, possibly_suspicious, signups.size)
    post_to_slack(report)
    post_to_response_url(response_url, "Audit complete. Report posted to admin channel.")
  rescue => e
    Rails.logger.error "[GuildAudit] Job failed: #{e.class}: #{e.message}\n#{e.backtrace&.first(5)&.join("\n")}"
    post_to_response_url(response_url, "Audit failed: #{e.message}") if response_url.present?
    raise
  end

  private

  def random_name?(name)
    return false if name.blank?
    return true if name.match?(/\A\d+\z/)                     # all digits
    return true if name.match?(/\A[a-z0-9]{6,}\z/) && vowel_ratio(name) < 0.15
    return true if name.match?(/\A[^a-zA-Z]*\z/) && name.size > 2  # no letters at all
    false
  end

  def autogenerated_email?(local_part)
    return false if local_part.blank?
    return true if local_part.match?(/\A[a-f0-9]{10,}\z/)
    return true if local_part.match?(/\A[a-z0-9]{8,}\z/) && local_part.count("0-9") >= (local_part.length * 0.4).ceil && vowel_ratio(local_part) < 0.15
    return true if local_part.match?(/\A[a-f0-9]{8}-[a-f0-9]{4}/)
    return true if local_part.length >= 16 && vowel_ratio(local_part) < 0.1
    false
  end

  def vowel_ratio(str)
    return 0.0 if str.blank?
    letters = str.gsub(/[^a-zA-Z]/, "")
    return 0.0 if letters.empty?
    vowels = letters.count("aeiouAEIOU").to_f
    vowels / letters.length
  end

  def build_report(definitely_suspicious, possibly_suspicious, total_signups)
    lines = []
    lines << "*Potential Signup Fraud Report*"
    lines << "Scanned #{total_signups} total signups across all guilds.\n"

    if definitely_suspicious.any?
      lines << "*Definitely Suspicious (#{definitely_suspicious.size}):*"
      definitely_suspicious.group_by { |d| d[:signup].guild }.each do |guild, entries|
        lines << "\n*#{guild&.name || 'Unknown Guild'}:*"
        entries.each do |entry|
          s = entry[:signup]
          flags = entry[:flags].join(", ")
          slack = s.user&.slack_id.present? ? " (<@#{s.user.slack_id}>)" : ""
          lines << "> #{s.name} (`#{s.email}`)#{slack}, #{flags}"
        end
      end
    else
      lines << "No definitely suspicious signups found."
    end

    lines << ""

    if possibly_suspicious.any?
      lines << "*Possibly Suspicious (#{possibly_suspicious.size}):*"
      possibly_suspicious.group_by { |p| p[:signup].guild }.each do |guild, entries|
        lines << "\n*#{guild&.name || 'Unknown Guild'}:*"
        entries.each do |entry|
          s = entry[:signup]
          flags = entry[:flags].join(", ")
          slack = s.user&.slack_id.present? ? " (<@#{s.user.slack_id}>)" : ""
          lines << "> #{s.name} (`#{s.email}`)#{slack}, #{flags}"
        end
      end
    else
      lines << "No possibly suspicious signups found."
    end

    lines << "\n*Summary:* #{definitely_suspicious.size} definite, #{possibly_suspicious.size} possible flags out of #{total_signups} signups."

    lines.join("\n")
  end

  def post_to_slack(message)
    return unless ENV["GUILDS_ADMIN_CHANNEL"].present?
    slack_client = Slack::Web::Client.new(token: ENV["GUILDS_BOT_TOKEN"])

    if message.length <= 3900
      slack_client.chat_postMessage(channel: ENV["GUILDS_ADMIN_CHANNEL"], text: message)
    else
      chunks = split_message(message, 3900)
      chunks.each { |chunk| slack_client.chat_postMessage(channel: ENV["GUILDS_ADMIN_CHANNEL"], text: chunk) }
    end
  rescue => e
    Rails.logger.error "[GuildAudit] Failed to post to admin channel: #{e.message}"
  end

  def split_message(message, max_length)
    chunks = []
    current = ""
    message.each_line do |line|
      if current.length + line.length > max_length
        chunks << current
        current = ""
      end
      current << line
    end
    chunks << current if current.present?
    chunks
  end

  def post_to_response_url(response_url, text)
    uri = URI.parse(response_url)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(uri.path, "Content-Type" => "application/json")
    request.body = { response_type: "in_channel", text: text }.to_json
    http.request(request)
  rescue => e
    Rails.logger.error "[GuildAudit] Failed to post result to response_url: #{e.message}"
  end
end
